### ISSUE TITLE
"sign_cmd" execution

### ISSUE THREAD

**Issue by stephen-fox** [richfelker/bakelite#1]
Hello,

I was poking through the code and noticed that the configurable`sign_cmd` program is executed in a shell:

```c
// store.c - line 115.
posix_spawnp(&pid, "sh", &fa, 0, (char *[])
    { "sh", "-c", (char *)signing_cmd, 0 },
    environ))
```

I realize this is likely administratively controlled (not subject to untrusted input). However, I do worry about users foot-gunning themselves because they did not realize their program and its arguments are subject to shell-isms. Would you be open to executing `sign_cmd` directly without wrapping it in `sh -c "<prog>"`?

Thank you for publishing this project.

**Comment by richfelker** [comment]
Some notes on the (pre-git I think) history here: this code was originally designed not for a model with a directory full of configuration, but needing the user to invoke bakelite with all parameters in command line arguments. In that usage, without needing a separate script file, you *need* a shell to be able to invoke a meaningful command here. It's not a footgun but the only way it can work. In the current scheme running `sign_cmd` from the config/localindex directory, the above `signing_cmd` variable is a fixed string `"./sign_cmd"`. The code in `store.c` still admits both uses, and I tentatively plan to "bring back" the (advanced) ability to invoke `bakelite backup` yourself with all the config state on the command line if you really want to (it's still partly there but not behaving consistently).
