### ISSUE TITLE
compile fails with 'REG_OK' undeclared

### ISSUE THREAD

**Issue by Gnarflord** [richfelker/bakelite#2]
Hey Rich,

we wrote earlier on Twitter. I'd like to add bakelite to the Arch User Repository (AUR) but the package doesn't compile anymore. I know this is very much WIP so I'll fix the AUR PKGBUILD at commit [9e70abd](https://github.com/richfelker/bakelite/commit/be61d40d67f9a4211b85039853dd9a7dc3620e29), which is the latest commit which compiles successfully.

The error appears in `match.c`:
```
> make
cc -g -O3 -Wall -o match.o -c match.c
match.c: In function ‘matcher_matches’:
match.c:148:16: error: ‘REG_OK’ undeclared (first use in this function)
  148 |         if (r==REG_OK) return 1;
      |                ^~~~~~
```

As soon as it compiles again I'll switch the AUR to the main branch instead. As there is currently no versioning on the project I've setup the system to build a version number from the number of commits and the commit hash, e.g. pkgver=r70.9e70abd
But if you like we can also switch to a tag-based system.

The AUR-entry should be up the next few days, I look forward to maintaining this :)

Greetings,
Jan

**Comment by richfelker** [comment]
Thanks for the report! Fixed by 0bb9d7f2c3da89a3444a5fdca0c0e8d8255377ef.
